import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { AppBreadCrumb } from "~/components/app-breadcrumb";
import { AppSidebar } from "~/components/app-sidebar";
import { SidebarProvider, SidebarTrigger } from "~/components/ui/sidebar";
import { Toaster } from "~/components/ui/sonner";
import { TooltipProvider } from "~/components/ui/tooltip";
import { TRPCReactProvider } from "~/trpc/react";

import { StoreProvider } from "./store/storeProvider";

export const metadata: Metadata = {
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
  title: "Create T3 App",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html className={`${GeistSans.variable}`} lang="en">
      <body>
        <TRPCReactProvider>
          <StoreProvider>
            <TooltipProvider>
              <SidebarProvider>
                <AppSidebar />
                <main className="w-full">
                  <div className="flex items-center space-x-4 p-4">
                    <SidebarTrigger />
                    <AppBreadCrumb />
                  </div>
                  <div className="border p-4">{children}</div>
                </main>
                <Toaster />
              </SidebarProvider>
            </TooltipProvider>
          </StoreProvider>
        </TRPCReactProvider>
        {/* not needed only for loading external AI chat pop up widget */}
        {/* <div id="chatWidget"></div> */}
      </body>
    </html>
  );
}
